version: "3.9"
services:
  frigate:
    container_name: frigate
    image: frigate:latest-tensorrt-jp5
    runtime: nvidia
    privileged: true
    restart: unless-stopped
    shm_size: "128mb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
      - "5678:5678"
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      YOLO_MODELS: "yolov7-320"