#!/command/with-contenv bash
if [ ! -f /config/model_cache/tensorrt/modified_yolow-l.trt ]; then
    mkdir -p /config/model_cache/tensorrt
    cp /usr/src/tensorrt/bin/trtexec /usr/bin
    trtexec --onnx=/config/modified_yolow-l.onnx --saveEngine=/config/model_cache/tensorrt/modified_yolow-l.trt --fp16
fi